//
//  TJLToken.swift
//  TJLexerTests
//
//  Created by Tjienta Vara on 2017-06-15.
//

import Foundation

class TJToken {
    var location: TJParserLocation!
    var match: Substring!
    let context: Int
    let optionalValue: Any?

    init(_ optionalValue: Any? = nil, context: Int = 0) {
        self.context = context
        self.optionalValue = optionalValue
    }
}

/** End of text was found, the lexer will not accept more request to getToken().
 * This token may be returned by a TJLexerAction, or may be generated by the lexer
 * when the end-of-text has been reached.
 */
class TJEndToken : TJToken {
}

/** This token can be returned by TJLexerAction to denote that the text may be skipped.
 * This token will not be returned to the parser by the lexer.
 */
class TJEmptyToken : TJToken {
}

/** This token can be returned by TJLexerAction to carry forward the current matched text
 * to the next call to TJLexerAction.
 * This token will not be returned to the parser by the lexer.
 */
class TJMoreToken : TJToken {
}

/** This token will be returned by the lexer when it can not match any tokens.
 */
class TJUnknownToken : TJToken {
}
